apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-argocd-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-argocd
  template:
    metadata:
      labels:
        app: hello-world-argocd
    spec:
      containers:
      - name: hello-world-argocd-container
        image: nginxdemos/hello:latest
        ports:
        - containerPort: 80
