apiVersion: v1
kind: Service
metadata:
  name: hello-world-argocd-service
spec:
  selector:
    app: hello-world-argocd
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort